const $=id=>document.getElementById(id);let panel=[],ranked=[],current=[];
const sampleCandidates=`candidate_id,target_id,canonical_sequence,predicted_affinity_score,selectivity_score,developability_score,evidence_domain_score,uncertainty_score,cluster_id
CAND-001,TARGET-01,CADEFGHIC,0.84,0.78,0.70,0.82,0.60,CL-01
CAND-002,TARGET-01,CWQKPGTLC,0.79,0.86,0.72,0.76,0.68,CL-02
CAND-003,TARGET-01,CNRTYCGHWFQKC,0.88,0.75,0.63,0.80,0.57,CL-03
CAND-004,TARGET-01,ASDFGHKLM,0.74,0.81,0.77,0.71,0.65,CL-04`;
const sampleFeedback=`candidate_id,round,ngs_input_count,ngs_selected_count,target_binding_mfi,display_mfi,off_target_signal,stability_signal,function_signal,topology_consistency
CAND-001,1,1000,8200,820,410,0.10,0.72,0.66,0.90
CAND-002,1,1200,6100,760,460,0.18,0.78,0.61,0.88
CAND-003,1,800,7200,900,390,0.08,0.68,0.74,0.80
CAND-004,1,1100,300,240,520,0.40,0.75,0.30,0.25`;
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const split=line=>{let a=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){a.push(v);v=''}else v+=c}a.push(v);return a};const h=split(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(h.map((k,i)=>[k,split(line)[i]??''])))}
function csv(rows){if(!rows.length)return'';const h=Object.keys(rows[0]),esc=v=>{v=String(v??'');return /[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v};return [h.join(','),...rows.map(r=>h.map(k=>esc(r[k])).join(','))].join('\n')}
async function post(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className=error?'show error':'show';setTimeout(()=>t.className='',2800)}
function render(rows,title){current=rows;$('result-title').textContent=title;$('download').disabled=!rows.length;if(!rows.length)return;const preferred=['candidate_id','peptide_sequence','backend','display_status','displayability_score','macrocycle_topology','prior_model_score','posterior_score','binding_display_ratio','acquisition_score','dna_insert'];const keys=[...preferred.filter(k=>k in rows[0]),...Object.keys(rows[0]).filter(k=>!preferred.includes(k))].slice(0,12);$('thead').innerHTML='<tr>'+keys.map(k=>`<th>${k.replaceAll('_',' ')}</th>`).join('')+'</tr>';$('tbody').innerHTML=rows.map(r=>'<tr>'+keys.map(k=>`<td>${r[k]??''}</td>`).join('')+'</tr>').join('');const direct=rows.filter(r=>r.display_status==='DIRECT_DISPLAY').length,review=rows.filter(r=>r.display_status==='DISPLAY_REVIEW').length,top=rows[0].posterior_score||rows[0].acquisition_score||rows[0].prior_model_score||'—';$('metrics').innerHTML=`<div class="metric"><strong>${rows.length}</strong><span>candidates</span></div><div class="metric"><strong>${direct}</strong><span>direct display</span></div><div class="metric"><strong>${review}</strong><span>review route</span></div><div class="metric"><strong>${top}</strong><span>top score</span></div>`}
async function screen(){try{const candidates=parseCSV($('candidates').value);if(!candidates.length)throw Error('Add candidate CSV first');const j=await post('/api/export',{backend:$('backend').value,limit:+$('limit').value,candidates});panel=j.rows;ranked=[];render(panel,'Display-ready candidates');toast(`${j.count} candidates screened`)}catch(e){toast(e.message,true)}}
async function learn(){try{if(!panel.length)throw Error('Screen candidates first');const results=parseCSV($('feedback').value);const j=await post('/api/feedback',{panel,results,limit:+$('limit').value});ranked=j.rows;render(ranked,'Posterior ranking after NGS / FACS');toast('Posterior ranking updated')}catch(e){toast(e.message,true)}}
async function design(){try{const base=ranked.length?ranked:panel;if(!base.length)throw Error('Screen candidates first');const j=await post('/api/design',{backend:$('backend').value,ranked:base,limit:+$('limit').value,parents:+$('parents').value,variants_per_parent:+$('variants').value});render(j.rows,'Next-round variant panel');toast(`${j.count} next-round variants generated`)}catch(e){toast(e.message,true)}}
async function simulate(){try{const candidates=parseCSV($('candidates').value);if(candidates.length<2)throw Error('Add at least two candidate sequences');const parameters={rounds:+$('sim-rounds').value,target_concentration_nm:+$('sim-target').value,ngs_reads:+$('sim-reads').value,seed:+$('sim-seed').value};const j=await post('/api/simulate-mrna',{candidates,parameters});render(j.final_ranking,'Final mRNA-display ranking');const first=j.round_summaries[0],last=j.round_summaries.at(-1);$('sim-summary').innerHTML=`<div class="metric"><strong>${last.round}</strong><span>rounds simulated</span></div><div class="metric"><strong>${last.top_candidate}</strong><span>top candidate</span></div><div class="metric"><strong>${(100*last.top_frequency).toFixed(2)}%</strong><span>final frequency</span></div><div class="metric"><strong>${first.effective_diversity} → ${last.effective_diversity}</strong><span>effective diversity</span></div>`;toast('mRNA display simulation complete')}catch(e){toast(e.message,true)}}
function loadFile(input,target){input.addEventListener('change',async()=>{if(input.files[0])$(target).value=await input.files[0].text()})}
$('sample').onclick=()=>{$('candidates').value=sampleCandidates;$('feedback').value=sampleFeedback;toast('Example data loaded')};$('screen').onclick=screen;$('learn').onclick=learn;$('design').onclick=design;$('simulate').onclick=simulate;$('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv(current)],{type:'text/csv'}));a.download='litrapid_results.csv';a.click();URL.revokeObjectURL(a.href)};loadFile($('candidate-file'),'candidates');loadFile($('feedback-file'),'feedback');$('candidates').value=sampleCandidates;$('feedback').value=sampleFeedback;
